/*
 * Copyright (C) 2014 Abhishek
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package userInterface.FDA;

import baseClasses.DrugAdmin.DrugAdmin;
import baseClasses.citizen.Citizen;

import baseClasses.enterprise.CityEnterprise;
import baseClasses.enterprise.CountryEnterprise;
import baseClasses.enterprise.Enterprise;
import baseClasses.enterprise.FDAEnterprise;
import baseClasses.enterprise.StateEnterprise;
import baseClasses.network.Network;
import baseClasses.organization.CitizenOrganization;
import baseClasses.organization.DrugAdminOrganization;
import baseClasses.organization.Organization;
import baseClasses.person.Person;
import baseClasses.roles.DrugAdminRole;

import java.util.ArrayList;
import java.util.regex.Pattern;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import userInterface.government.EditCitizenDetails;
import userInterface.hospital.ViewCitizenDetails;

/**
 *
 * @author Abhishek
 */
public class AddNewDrugAdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddNewDrugAdminPanel
     */
    Network internationalNetwork;
    ArrayList<FDAEnterprise> docFDAsList;
    DrugAdmin drugAdmin = new DrugAdmin();
    FDAEnterprise fdaEnterprise;
    Citizen finalCitizen = null;

    public AddNewDrugAdminPanel(Network internationalNetwork, FDAEnterprise fdaEnterprise) {
        initComponents();
        this.internationalNetwork = internationalNetwork;
        this.fdaEnterprise = fdaEnterprise;
        txtUID.setEnabled(false);
        txtPassword.setEnabled(false);
        txtUsername.setEnabled(false);
        txtPassword1.setEnabled(false);
        docFDAsList = new ArrayList();
        populateCountryList(cmbCountryList);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblName2 = new javax.swing.JLabel();
        txtUID = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        lblName3 = new javax.swing.JLabel();
        cmbCountryList = new javax.swing.JComboBox();
        lblResult = new javax.swing.JLabel();
        btnSaveDrugAdmin = new javax.swing.JButton();
        lblSelectCountry5 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblSelectCountry6 = new javax.swing.JLabel();
        btnViewProfile = new javax.swing.JButton();
        lblSelectCountry7 = new javax.swing.JLabel();
        txtPassword1 = new javax.swing.JPasswordField();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseClasses/healtech logo.PNG"))); // NOI18N

        lblName1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblName1.setForeground(new java.awt.Color(0, 153, 51));
        lblName1.setText("             Add New Drug Admin");

        lblName2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName2.setForeground(new java.awt.Color(0, 153, 51));
        lblName2.setText("Search by Citizen ID");

        txtUID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnSearch.setBackground(new java.awt.Color(255, 255, 255));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(0, 153, 0));
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        lblName3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName3.setForeground(new java.awt.Color(0, 153, 51));
        lblName3.setText("Select Country");

        cmbCountryList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbCountryList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCountryListActionPerformed(evt);
            }
        });

        lblResult.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblResult.setForeground(new java.awt.Color(0, 153, 51));

        btnSaveDrugAdmin.setBackground(new java.awt.Color(255, 255, 255));
        btnSaveDrugAdmin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnSaveDrugAdmin.setForeground(new java.awt.Color(0, 153, 0));
        btnSaveDrugAdmin.setText("Save Drug Admin Profile");
        btnSaveDrugAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveDrugAdminActionPerformed(evt);
            }
        });

        lblSelectCountry5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSelectCountry5.setForeground(new java.awt.Color(0, 153, 51));
        lblSelectCountry5.setText("Username");

        txtUsername.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        lblSelectCountry6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSelectCountry6.setForeground(new java.awt.Color(0, 153, 51));
        lblSelectCountry6.setText("Password");

        btnViewProfile.setBackground(new java.awt.Color(255, 255, 255));
        btnViewProfile.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnViewProfile.setForeground(new java.awt.Color(0, 153, 0));
        btnViewProfile.setText("View Profile");
        btnViewProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewProfileActionPerformed(evt);
            }
        });

        lblSelectCountry7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSelectCountry7.setForeground(new java.awt.Color(0, 153, 51));
        lblSelectCountry7.setText("Re-enter Password");

        txtPassword1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName1, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblName3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbCountryList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblName2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtUID, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSelectCountry5)
                                            .addComponent(lblSelectCountry6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblSelectCountry7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnViewProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(481, 481, 481)
                        .addComponent(btnSaveDrugAdmin)))
                .addGap(0, 574, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblName1)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnViewProfile)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblName3)
                            .addComponent(cmbCountryList, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblName2)
                            .addComponent(txtUID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch))
                        .addGap(25, 25, 25)
                        .addComponent(lblResult, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSelectCountry5)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectCountry6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSelectCountry7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(btnSaveDrugAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        System.out.println("in the search button method in add new drugAdmin panel");
        CountryEnterprise countryEnterprise = (CountryEnterprise) cmbCountryList.getSelectedItem();
        System.out.println("Country enterprise sel" + countryEnterprise);
        int UID = Integer.parseInt(txtUID.getText());
        System.out.println(UID);
        StateEnterprise stateEnterprise = null;
        CityEnterprise cityEnterprise = null;
        Citizen citizen = null;

        CountryEnterprise countryEnt = null;
        CitizenOrganization citizenOrganization = null;
        DrugAdminOrganization drugAdminOrganization = null;

        for (Enterprise country : internationalNetwork.getEnterpriseDirectory().getEnterpriseList()) {
            if (country.getClass() == CountryEnterprise.class) {
                countryEnt = (CountryEnterprise) country;

                if (countryEnt.getName().equals(countryEnterprise.getName())) {
                    System.out.println("Country found: " + countryEnt);
                    countryEnterprise = countryEnt;
                    for (Enterprise state : countryEnterprise.getCountryNetwork().getEnterpriseDirectory().getEnterpriseList()) {
                        if (state.getClass() == StateEnterprise.class) {
                            stateEnterprise = (StateEnterprise) state;

                            for (Enterprise city : stateEnterprise.getStateNetwork().getEnterpriseDirectory().getEnterpriseList()) {
                                cityEnterprise = (CityEnterprise) city;

                                for (Organization organization : cityEnterprise.getOrganizationDirectory().getOrganizationList()) {
                                    if (organization.getClass() == CitizenOrganization.class) {
                                        citizenOrganization = (CitizenOrganization) organization;
                                        for (Person person : citizenOrganization.getPersonDirectory().getPersonList()) {
                                            if (person.getClass() == Citizen.class) {
                                                citizen = (Citizen) person;
                                                System.out.println("" + cityEnterprise.getName() + " " + person.getName().getFirstName() + " " + cityEnterprise.getPersonDirectory().getPersonList().size());
                                                if (citizen.getUID() == UID) {
                                                    finalCitizen = citizen;
                                                    lblResult.setText("Profile Found: " + finalCitizen.getName().getFirstName());
                                                    System.out.println("Profile found in Add DrugAdmin Panel" + fdaEnterprise.getOrganizationDirectory().getOrganizationList().size());
                                                    System.out.println(fdaEnterprise);
                                                    System.out.println(fdaEnterprise.getOrganizationDirectory());
                                                    System.out.println(fdaEnterprise.getOrganizationDirectory().getOrganizationList());

                                                    for (Organization drugAdminOrg : fdaEnterprise.getOrganizationDirectory().getOrganizationList()) {
                                                        if (drugAdminOrg.getClass() == DrugAdminOrganization.class) {
                                                            drugAdminOrganization = (DrugAdminOrganization) drugAdminOrg;

                                                            //drugAdmin.setHighestDegree(txtHightestDegree1.getText());
                                                            //drugAdmin.setSpecialization(txtSpecialization.getText());
                                                            drugAdmin.setAddress(finalCitizen.getAddress());
                                                            drugAdmin.setDateOfBirth(finalCitizen.getDateOfBirth());
                                                            drugAdmin.setName(finalCitizen.getName());
                                                            drugAdmin.setNationality(finalCitizen.getNationality());

                                                            drugAdmin.setUID(UID);

                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }

                                }

                            }
                        }
                    }
                }
            }
        }

        


    }//GEN-LAST:event_btnSearchActionPerformed

    private void cmbCountryListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCountryListActionPerformed
        // TODO add your handling code here:
        txtUID.setEnabled(true);
        txtPassword.setEnabled(true);
        txtPassword1.setEnabled(true);
        txtUsername.setEnabled(true);

    }//GEN-LAST:event_cmbCountryListActionPerformed

    private void btnSaveDrugAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveDrugAdminActionPerformed
        // TODO add your handling code here:

        
        
        
        
        if (!(txtUsername.getText().isEmpty())) {
            if (!(String.valueOf(txtPassword.getPassword()).equals(""))) {
                if (!(String.valueOf(txtPassword1.getPassword()).equals(""))) {
                    if (((Pattern.matches("^[a-zA-Z\\s ?]+", txtUsername.getText())))) {
                        String one = String.valueOf(txtPassword.getPassword());
                    String two = String.valueOf(txtPassword1.getPassword());
                    if (one.equals(two)) {
                            drugAdmin.setUID(Integer.parseInt(txtUID.getText()));

                            //fdaEnterprise.getPersonDirectory().getPersonList().add(drugAdmin);
                            DrugAdminOrganization drugAdminOrganization = null;
                            System.out.println("Printing from Save Drug Admin" + fdaEnterprise + "  " + fdaEnterprise.getOrganizationDirectory().getOrganizationList().size() + "DrugAdmin: " + drugAdmin);
                            System.out.println(fdaEnterprise.getOrganizationDirectory());
                            Person tempPersonn = drugAdmin;

                            for (Organization organization : fdaEnterprise.getOrganizationDirectory().getOrganizationList()) {
                                if (organization.getClass() == DrugAdminOrganization.class) {
                                    drugAdminOrganization = (DrugAdminOrganization) organization;
                                    drugAdminOrganization.getPersonDirectory().getPersonList().add(drugAdmin);

                                    drugAdminOrganization.getUserAccountDirectory().createUserAccount(txtUsername.getText(), 
                                            String.valueOf(txtPassword.getPassword()), new DrugAdminRole(), "Active", tempPersonn);

                                }
                            }
                        }
                        else
                            JOptionPane.showMessageDialog(this, "The two passwords entered do not match", "Error", JOptionPane.ERROR_MESSAGE);

                    }
                    else
                        JOptionPane.showMessageDialog(this, "Please enter valid characters in the username textbox", "Error", JOptionPane.ERROR_MESSAGE);
                }
                else
                    JOptionPane.showMessageDialog(this, "Please enter the password in both the fields", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else
                    JOptionPane.showMessageDialog(this, "Please enter the password in both the fields", "Error", JOptionPane.ERROR_MESSAGE);
        }
        else
                    JOptionPane.showMessageDialog(this, "Please enter the username", "Error", JOptionPane.ERROR_MESSAGE);


    }//GEN-LAST:event_btnSaveDrugAdminActionPerformed

    private void btnViewProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewProfileActionPerformed
        // TODO add your handling code here:
        //JFrame detailsFrame = new JFrame("View Citizen Profile");

        JFrame frame = new JFrame(finalCitizen.getName().getFirstName() + " " + finalCitizen.getName().getLastName());
        frame.setSize(1200, 1000);

        frame.setVisible(true);
        frame.add(new ViewCitizenDetails(internationalNetwork, finalCitizen, null));
    }//GEN-LAST:event_btnViewProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveDrugAdmin;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnViewProfile;
    private javax.swing.JComboBox cmbCountryList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblResult;
    private javax.swing.JLabel lblSelectCountry5;
    private javax.swing.JLabel lblSelectCountry6;
    private javax.swing.JLabel lblSelectCountry7;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPassword1;
    private javax.swing.JTextField txtUID;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
 private void populateCountryList(JComboBox cmbCountryList) {
        cmbCountryList.removeAllItems();
        CountryEnterprise countryEnterprise;

        for (Enterprise country : internationalNetwork.getEnterpriseDirectory().getEnterpriseList()) {
            cmbCountryList.addItem((CountryEnterprise) country);
        }

    }

}
