/*
 * Copyright (C) 2014 Abhishek
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package userInterface.pharmacy;

import baseClasses.enterprise.Enterprise;
import baseClasses.enterprise.PharmacyEnterprise;
import baseClasses.network.Network;
import baseClasses.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Abhishek
 */
public class PharmacyAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form GovernmentAdminWorkArea
     */
    Network internationalNetwork;
    UserAccount userAccount;
    private Enterprise inEnterprise;
    private PharmacyEnterprise pharmacyEnterprise;
    
    public PharmacyAdminWorkArea(Network internationalNetwork, UserAccount userAccount, Enterprise inEnterprise) {
        initComponents();
        this.internationalNetwork = internationalNetwork;
        this.userAccount = userAccount;
                 this.inEnterprise = inEnterprise;
                 
                 if(inEnterprise.getClass() == PharmacyEnterprise.class)
                 {
                     pharmacyEnterprise = (PharmacyEnterprise) inEnterprise;
                 }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnManagePharmacies = new javax.swing.JButton();
        btnPurchaseMedicineByManufacturer = new javax.swing.JButton();
        btnManageOrders = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnManagePharmacies.setBackground(new java.awt.Color(255, 255, 255));
        btnManagePharmacies.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManagePharmacies.setForeground(new java.awt.Color(0, 153, 0));
        btnManagePharmacies.setText("Manage Drug Inventory");
        btnManagePharmacies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePharmaciesActionPerformed(evt);
            }
        });

        btnPurchaseMedicineByManufacturer.setBackground(new java.awt.Color(255, 255, 255));
        btnPurchaseMedicineByManufacturer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPurchaseMedicineByManufacturer.setForeground(new java.awt.Color(0, 153, 0));
        btnPurchaseMedicineByManufacturer.setText("Purchase Medicines By Manufacturer");
        btnPurchaseMedicineByManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPurchaseMedicineByManufacturerActionPerformed(evt);
            }
        });

        btnManageOrders.setBackground(new java.awt.Color(255, 255, 255));
        btnManageOrders.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManageOrders.setForeground(new java.awt.Color(0, 153, 0));
        btnManageOrders.setText("Manage Orders");
        btnManageOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnPurchaseMedicineByManufacturer, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)
                .addComponent(btnManagePharmacies, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(424, 424, 424)
                .addComponent(btnManageOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManagePharmacies)
                    .addComponent(btnPurchaseMedicineByManufacturer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnManageOrders)
                .addGap(24, 24, 24))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseClasses/healtech logo.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 1196, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 465, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagePharmaciesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePharmaciesActionPerformed
        // TODO add your handling code here:
        JPanel manageCitizenDetailsCard = new JPanel();
        manageCitizenDetailsCard.setLayout(new CardLayout());
        
        manageCitizenDetailsCard.add(new ManagePharmacyProfiles(internationalNetwork,manageCitizenDetailsCard));
        CardLayout layout = (CardLayout) manageCitizenDetailsCard.getLayout();
        layout.next(manageCitizenDetailsCard);
        
        jSplitPane1.setRightComponent(manageCitizenDetailsCard);
    }//GEN-LAST:event_btnManagePharmaciesActionPerformed

    private void btnPurchaseMedicineByManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPurchaseMedicineByManufacturerActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new PurchaseByManufacturer(internationalNetwork, userAccount, pharmacyEnterprise));
        
    }//GEN-LAST:event_btnPurchaseMedicineByManufacturerActionPerformed

    private void btnManageOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrdersActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setBottomComponent(new MedicineOrderRequestDetailsPanel(pharmacyEnterprise, userAccount));
    }//GEN-LAST:event_btnManageOrdersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageOrders;
    private javax.swing.JButton btnManagePharmacies;
    private javax.swing.JButton btnPurchaseMedicineByManufacturer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
