/*
 * Copyright (C) 2014 Abhishek
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package userInterface.government;

import baseClasses.network.Network;
import baseClasses.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Abhishek
 */
public class GovernmentAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form GovernmentAdminWorkArea
     */
    private Network internationalNetwork;
    private UserAccount userAccount;
    
    public GovernmentAdminWorkArea(Network internationalNetwork, UserAccount userAccount) {
        initComponents();
        this.internationalNetwork = internationalNetwork;
        this.userAccount = userAccount;
                 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnAddNewCitizen = new javax.swing.JButton();
        btnManageCitizenDetails = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(100);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAddNewCitizen.setBackground(new java.awt.Color(255, 255, 255));
        btnAddNewCitizen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddNewCitizen.setForeground(new java.awt.Color(0, 153, 0));
        btnAddNewCitizen.setText("Add New Citizen");
        btnAddNewCitizen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewCitizenActionPerformed(evt);
            }
        });

        btnManageCitizenDetails.setBackground(new java.awt.Color(255, 255, 255));
        btnManageCitizenDetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManageCitizenDetails.setForeground(new java.awt.Color(0, 153, 0));
        btnManageCitizenDetails.setText("Manage Citizen Details");
        btnManageCitizenDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCitizenDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddNewCitizen, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(btnManageCitizenDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNewCitizen)
                    .addComponent(btnManageCitizenDetails))
                .addGap(0, 33, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseClasses/healtech logo.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 571, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 332, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewCitizenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewCitizenActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new CreateNewCitizenPanel(internationalNetwork, userAccount.getUsername()));
        
    }//GEN-LAST:event_btnAddNewCitizenActionPerformed

    private void btnManageCitizenDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCitizenDetailsActionPerformed
        // TODO add your handling code here:
        JPanel manageCitizenDetailsCard = new JPanel();
        manageCitizenDetailsCard.setLayout(new CardLayout());
        jSplitPane1.setRightComponent(manageCitizenDetailsCard);
        manageCitizenDetailsCard.add(new ManageCitizenProfiles(internationalNetwork,manageCitizenDetailsCard, userAccount.getUsername()));
        CardLayout layout = (CardLayout) manageCitizenDetailsCard.getLayout();
        layout.next(manageCitizenDetailsCard);
    }//GEN-LAST:event_btnManageCitizenDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewCitizen;
    private javax.swing.JButton btnManageCitizenDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
