/*
 * Copyright (C) 2014 Abhishek
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package userInterface.distributor;

import baseClasses.enterprise.FDAEnterprise;
import baseClasses.enterprise.PharmaceuticalCompanyEnterprise;
import baseClasses.network.Network;
import baseClasses.organization.DistributorOrganization;
import baseClasses.organization.ManufacturingOrganization;
import baseClasses.organization.Organization;
import baseClasses.userAccount.UserAccount;

/**
 *
 * @author Abhishek
 */
public class DistributorWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form DoctorWorkAreaPanel
     */
    FDAEnterprise fdaEnterprise;
    Network internationalNetwork;
    private PharmaceuticalCompanyEnterprise pharmaceuticalCompanyEnterprise;
    private ManufacturingOrganization manufacturingOrganization;
    private UserAccount userAccount;
    private Organization inOrganization;
    private DistributorOrganization distributorOrganization = null;
    
    public DistributorWorkArea(Network internationalNetwork, PharmaceuticalCompanyEnterprise pharmaceuticalCompanyEnterprise, ManufacturingOrganization manufacturingOrganization, UserAccount userAccount, Organization inOrganization) {
        initComponents();
        this.fdaEnterprise = fdaEnterprise;
        this.internationalNetwork = internationalNetwork;
        this.pharmaceuticalCompanyEnterprise = pharmaceuticalCompanyEnterprise;
        this.manufacturingOrganization = manufacturingOrganization;
        this.userAccount = userAccount;
        
        if(inOrganization.getClass() == DistributorOrganization.class)
        {
            distributorOrganization = (DistributorOrganization) inOrganization;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCheckOrders = new javax.swing.JButton();
        btnManageOrders = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1515, 820));
        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(300);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseClasses/healtech logo.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 1160, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 733, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseClasses/healtech small.png"))); // NOI18N

        btnCheckOrders.setBackground(new java.awt.Color(255, 255, 255));
        btnCheckOrders.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCheckOrders.setForeground(new java.awt.Color(0, 153, 0));
        btnCheckOrders.setText("Check Orders");
        btnCheckOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckOrdersActionPerformed(evt);
            }
        });

        btnManageOrders.setBackground(new java.awt.Color(255, 255, 255));
        btnManageOrders.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManageOrders.setForeground(new java.awt.Color(0, 153, 0));
        btnManageOrders.setText("Manage Orders");
        btnManageOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrdersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCheckOrders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
            .addComponent(btnManageOrders, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnCheckOrders)
                .addGap(50, 50, 50)
                .addComponent(btnManageOrders)
                .addGap(0, 601, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckOrdersActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new OrderApprovals(pharmaceuticalCompanyEnterprise.getWorkQueue(), userAccount, manufacturingOrganization, pharmaceuticalCompanyEnterprise));
       
    }//GEN-LAST:event_btnCheckOrdersActionPerformed

    private void btnManageOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrdersActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new MedicineOrderRequestDetailsPanel(distributorOrganization, userAccount, pharmaceuticalCompanyEnterprise));
    }//GEN-LAST:event_btnManageOrdersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckOrders;
    private javax.swing.JButton btnManageOrders;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
