/*
 * Copyright (C) 2014 Abhishek
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package userInterface.pharmaceuticalCompany;

import baseClasses.Drug;
import baseClasses.enterprise.CityEnterprise;
import baseClasses.enterprise.CountryEnterprise;
import baseClasses.enterprise.Enterprise;
import baseClasses.enterprise.FDAEnterprise;
import baseClasses.enterprise.PharmaceuticalCompanyEnterprise;
import baseClasses.network.Network;
import baseClasses.userAccount.UserAccount;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import workQueue.DrugApprovalWorkRequest;

/**
 *
 * @author Abhishek
 */
public class AddNewDrug extends javax.swing.JPanel {

    /**
     * Creates new form SelectHospitalPanel
     */
    private Network internationalNetwork;

    private PharmaceuticalCompanyEnterprise pharmaceuticalCompanyEnterprise;
    private CityEnterprise inCityEnterprise;
    private CountryEnterprise countryEnterprise;
    private UserAccount userAccount;

    public AddNewDrug(Network internationalNetwork, PharmaceuticalCompanyEnterprise pharmaceuticalCompanyEnterprise, CityEnterprise inCityEnterprise, UserAccount userAccount) {
        initComponents();
        this.pharmaceuticalCompanyEnterprise = pharmaceuticalCompanyEnterprise;
        this.userAccount = userAccount;
        this.internationalNetwork = internationalNetwork;
        this.inCityEnterprise = inCityEnterprise;
        //this.countryEnterprise = countryEnterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblName3 = new javax.swing.JLabel();
        lblName4 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrugComponents = new javax.swing.JTable();
        btnSubmitForApproval = new javax.swing.JButton();
        btnAddToTable = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1515, 820));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseClasses/healtech logo.PNG"))); // NOI18N

        lblName1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblName1.setForeground(new java.awt.Color(0, 153, 51));
        lblName1.setText("                              Add New Drug");

        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        lblName3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName3.setForeground(new java.awt.Color(0, 153, 51));
        lblName3.setText("Drug Name");

        lblName4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblName4.setForeground(new java.awt.Color(0, 153, 51));
        lblName4.setText("Drug Component");

        txtName1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName1ActionPerformed(evt);
            }
        });

        tblDrugComponents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug Components"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDrugComponents);

        btnSubmitForApproval.setBackground(new java.awt.Color(255, 255, 255));
        btnSubmitForApproval.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnSubmitForApproval.setForeground(new java.awt.Color(0, 153, 0));
        btnSubmitForApproval.setText("Submit For Approval");
        btnSubmitForApproval.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitForApprovalActionPerformed(evt);
            }
        });

        btnAddToTable.setBackground(new java.awt.Color(255, 255, 255));
        btnAddToTable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddToTable.setForeground(new java.awt.Color(0, 153, 0));
        btnAddToTable.setText(">>");
        btnAddToTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToTableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(674, 674, 674)
                .addComponent(btnSubmitForApproval)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName4)
                                .addGap(18, 18, 18)
                                .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblName3)
                                .addGap(18, 18, 18)
                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(btnAddToTable)
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 476, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblName1)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName3))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblName4)
                            .addComponent(btnAddToTable)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(btnSubmitForApproval)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName1ActionPerformed

    private void btnSubmitForApprovalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitForApprovalActionPerformed
        // TODO add your handling code here:
        Drug drug = new Drug();
        drug.setName(txtName.getText());
        DefaultTableModel dtm = (DefaultTableModel) tblDrugComponents.getModel();
        int rowcount = dtm.getRowCount();

        for (int i = 0; i < rowcount; i++) {
            drug.addComponent((String) dtm.getValueAt(i, 0));
        }

        drug.setApprovalStatus("Pending");

        //PharmaceuticalCompanyEnterprise pharmaceuticalCompanyEnterprise = (PharmaceuticalCompanyEnterprise) inEnterprise;
        //pharmaceuticalCompanyEnterprise.addDrug(drug);
        DrugApprovalWorkRequest drugApprovalWorkRequest = new DrugApprovalWorkRequest(drug);
        drugApprovalWorkRequest.setSender(userAccount);
        drugApprovalWorkRequest.setDrug(drug);
        drugApprovalWorkRequest.setMessage("New Drug Approal Request");
        drugApprovalWorkRequest.setStatus("Sent For Approval");
        drugApprovalWorkRequest.setRequestDate(new Date());
        
        System.out.println("Printing from Add new drug Pharmaceutical Company enterprise" + pharmaceuticalCompanyEnterprise);
        System.out.println(pharmaceuticalCompanyEnterprise.getAddress());
        System.out.println(pharmaceuticalCompanyEnterprise.getAddress().getCountry());
        countryEnterprise = pharmaceuticalCompanyEnterprise.getAddress().getCountry();
        System.out.println(countryEnterprise);
        FDAEnterprise fdaEnterprise = null;
        String fdaName = countryEnterprise.getName() + "FDA";
        CountryEnterprise countryE, countryEnt = null;

        for (Enterprise country : internationalNetwork.getEnterpriseDirectory().getEnterpriseList()) {
            if (country.getClass() == CountryEnterprise.class) {
                countryE = (CountryEnterprise) country;

                if (countryE.getName().equals(countryEnterprise.getName())) {
                    countryEnt = countryE;

                    for (Enterprise fda : countryEnt.getCountryNetwork().getEnterpriseDirectory().getEnterpriseList()) {

                        if (fda.getClass() == FDAEnterprise.class) {

                            fdaEnterprise = (FDAEnterprise) fda;
                            System.out.println("FDAEnterprise found" + fdaEnterprise);
                            //if(fdaEnterprise.getName().equals(fdaName))
                            {
                                fda.getWorkQueue().getWorkRequestList().add(drugApprovalWorkRequest);
                                userAccount.getWorkQueue().getWorkRequestList().add(drugApprovalWorkRequest);
                                System.out.println("FDAEnterprise found" + fdaEnterprise);
                                System.out.println("work queue length" + fda.getWorkQueue().getWorkRequestList().size());
                            }

                        }
                    }

                }
            }
        }

        //drug.setComponentsInvolved((String[])tblDrugComponents.getComponents());

    }//GEN-LAST:event_btnSubmitForApprovalActionPerformed

    private void btnAddToTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToTableActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) tblDrugComponents.getModel();

        Object[] row = new Object[1];
        row[0] = txtName1.getText();
        dtm.addRow(row);


    }//GEN-LAST:event_btnAddToTableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToTable;
    private javax.swing.JButton btnSubmitForApproval;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName3;
    private javax.swing.JLabel lblName4;
    private javax.swing.JTable tblDrugComponents;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    // End of variables declaration//GEN-END:variables

}
