/*
 * Copyright (C) 2014 Abhishek
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package userInterface.pharmaceuticalCompany;

import baseClasses.Drug;
import baseClasses.enterprise.Enterprise;
import baseClasses.enterprise.PharmaceuticalCompanyEnterprise;
import baseClasses.userAccount.UserAccount;
import javax.swing.table.DefaultTableModel;
import workQueue.DrugApprovalWorkRequest;
import workQueue.WorkRequest;

/**
 *
 * @author Abhishek
 */
public class DrugRequestDetailsPanel extends javax.swing.JPanel {

    /**
     * Creates new form DrugRequestDetailsPanel
     */
    private Enterprise inEnterprise;
    private PharmaceuticalCompanyEnterprise pharmaceuticalCompanyEnterprise;
    private UserAccount userAccount;
    
    public DrugRequestDetailsPanel(PharmaceuticalCompanyEnterprise pharmaceuticalCompanyEnterprise, UserAccount userAccount) {
        initComponents();
        this.pharmaceuticalCompanyEnterprise = pharmaceuticalCompanyEnterprise;
        this.userAccount = userAccount;
        populateDrugTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblName1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDrugDetails = new javax.swing.JTable();
        btnAddToDrugList = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        lblName1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblName1.setForeground(new java.awt.Color(0, 153, 51));
        lblName1.setText("Drug Details ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseClasses/healtech logo.PNG"))); // NOI18N

        tblDrugDetails.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblDrugDetails.setForeground(new java.awt.Color(0, 204, 51));
        tblDrugDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Drug", "Status", "Notes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDrugDetails);
        if (tblDrugDetails.getColumnModel().getColumnCount() > 0) {
            tblDrugDetails.getColumnModel().getColumn(0).setResizable(false);
            tblDrugDetails.getColumnModel().getColumn(1).setResizable(false);
            tblDrugDetails.getColumnModel().getColumn(2).setResizable(false);
        }

        btnAddToDrugList.setBackground(new java.awt.Color(255, 255, 255));
        btnAddToDrugList.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddToDrugList.setForeground(new java.awt.Color(0, 153, 0));
        btnAddToDrugList.setText("Add to Approved Drug List");
        btnAddToDrugList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToDrugListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(556, 556, 556)
                .addComponent(btnAddToDrugList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 615, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(layout.createSequentialGroup()
                .addGap(358, 358, 358)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                    .addComponent(lblName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblName1)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnAddToDrugList)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddToDrugListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToDrugListActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDrugDetails.getSelectedRow();
        DrugApprovalWorkRequest drugApprovalWorkRequest = null;
        
        if(selectedRow > -1)
        {
            drugApprovalWorkRequest = (DrugApprovalWorkRequest) tblDrugDetails.getValueAt(selectedRow, 0);
            
            if(drugApprovalWorkRequest.getStatus().equals("Approved"))
            {
                pharmaceuticalCompanyEnterprise.getDrugList().add(drugApprovalWorkRequest.getDrug());
            }
        }

    }//GEN-LAST:event_btnAddToDrugListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToDrugList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName1;
    private javax.swing.JTable tblDrugDetails;
    // End of variables declaration//GEN-END:variables

    private void populateDrugTable()
    {
        DefaultTableModel dtm = (DefaultTableModel) tblDrugDetails.getModel();
        dtm.setRowCount(0);
        System.out.println("Printing from drug details panel");
        System.out.println("Pharma company" + pharmaceuticalCompanyEnterprise);
        System.out.println("druglist length: " + pharmaceuticalCompanyEnterprise.getDrugList());
        DrugApprovalWorkRequest drugApprovalWorkRequest = null;
        
        for(WorkRequest wr: userAccount.getWorkQueue().getWorkRequestList())
        {
            if(wr.getClass() == DrugApprovalWorkRequest.class)
            {
                drugApprovalWorkRequest = (DrugApprovalWorkRequest) wr;
                 Object[] row = new Object[2];
                 row[0] = drugApprovalWorkRequest;
                 row[1] = drugApprovalWorkRequest.getStatus();
                 dtm.addRow(row);
            }
        }

    }
}
