/*
 * Copyright (C) 2014 Abhishek
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package userInterface.pharmaceuticalCompany;


import baseClasses.manufacturer.Manufacturer;
import baseClasses.enterprise.CityEnterprise;
import baseClasses.enterprise.CountryEnterprise;
import baseClasses.enterprise.Enterprise;
import baseClasses.enterprise.PharmaceuticalCompanyEnterprise;
import baseClasses.enterprise.StateEnterprise;
import baseClasses.network.Network;
import baseClasses.organization.ManufacturingOrganization;
import baseClasses.organization.Organization;
import baseClasses.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhishek
 */

public class ManageManufacturerProfiles extends javax.swing.JPanel {

    /**
     * Creates new form ManageManufacturerProfiles
     */
    Network internationalNetwork;
    JPanel manageManufacturersProfileCard;
    PharmaceuticalCompanyEnterprise pharmaceuticalCompanyEnterprise;
    CityEnterprise inCityEnterprise;
    
    public ManageManufacturerProfiles(Network internationalNetwork, JPanel manageManufacturersProfileCard,PharmaceuticalCompanyEnterprise pharmaceuticalCompanyEnterprise,CityEnterprise inCityEnterprise) {
        initComponents();
        this.internationalNetwork = internationalNetwork;
        this.manageManufacturersProfileCard = manageManufacturersProfileCard;
        this.pharmaceuticalCompanyEnterprise= pharmaceuticalCompanyEnterprise;
        this.inCityEnterprise = inCityEnterprise;
        
        populateManuTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManufacturers = new javax.swing.JTable();
        btnShowDetails = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseClasses/healtech logo.PNG"))); // NOI18N

        lblName1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblName1.setForeground(new java.awt.Color(0, 153, 51));
        lblName1.setText("                      Manage Manufacturer Organization");

        tblManufacturers.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblManufacturers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Manufacturer"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManufacturers);
        if (tblManufacturers.getColumnModel().getColumnCount() > 0) {
            tblManufacturers.getColumnModel().getColumn(0).setResizable(false);
        }

        btnShowDetails.setBackground(new java.awt.Color(255, 255, 255));
        btnShowDetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnShowDetails.setForeground(new java.awt.Color(0, 153, 0));
        btnShowDetails.setText("Show Details");
        btnShowDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnShowDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(571, 571, 571))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(606, 606, 606)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(452, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(lblName1)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnShowDetails)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowDetailsActionPerformed
        // TODO add your handling code here:
      int selectedRow = tblManufacturers.getSelectedRow();
       Manufacturer manufacturer = (Manufacturer) tblManufacturers.getValueAt(selectedRow, 0);
              
       CardLayout layout = (CardLayout) manageManufacturersProfileCard.getLayout();
       manageManufacturersProfileCard.add(new EditManufacturerDetails(internationalNetwork));
       layout.next(manageManufacturersProfileCard);
      //this.add(new EditManufacturerDetails((internationalNetwork,manufacturer)));
              

    }//GEN-LAST:event_btnShowDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnShowDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName1;
    private javax.swing.JTable tblManufacturers;
    // End of variables declaration//GEN-END:variables
    
    
    public void populateManuTable()
    {
        CityEnterprise cityEnterprise =inCityEnterprise;
        ManufacturingOrganization manufacturingOrganization = null;
        boolean flag = false;
        Manufacturer manufacturer = null;
        
        DefaultTableModel dtm = (DefaultTableModel) tblManufacturers.getModel();
        dtm.setRowCount(0);
        System.out.println(cityEnterprise.getOrganizationDirectory().getOrganizationList().size());
        
         for(Organization organization: pharmaceuticalCompanyEnterprise.getOrganizationDirectory().getOrganizationList())
                {
                       if(organization.getClass() == ManufacturingOrganization.class)
                        {
                            manufacturingOrganization = (ManufacturingOrganization) organization;
                            //manufacturingOrganization.getPersonDirectory().getPersonList().add(manufacturing);
                            System.out.println("Printing from manage manu profiles: size "+manufacturingOrganization.getUserAccountDirectory().getUserAccountList().size());
                            for(UserAccount ua: manufacturingOrganization.getUserAccountDirectory().getUserAccountList())
                            {
                                    Object[] row = new Object[1];
                                    row[0] = ua.getPerson();
                                    System.out.println(ua.getPerson());
                                    dtm.addRow(row);

                            }
                            //manufacturingOrganization.getUserAccountDirectory().createUserAccount(txtUsername.getText(), String.valueOf(txtPassword.getPassword()), new ManufacturingRole(), "Active",manufacturing);
                            //ManufacturingOrganization manufacturingOrganization = (ManufacturingOrganization) pharmaceu
                            //HospitalEnterprise hospitalEnterprise = (HospitalEnterprise) cityEnterprise.getCityNetwork().getEnterpriseDirectory().
                                    //createAndAddEnterprise(txtHospitalName.getText(), Enterprise.EnterpriseType.Hospital,txtUsername.getText(), String.valueOf(txtPassword.getPassword()), new AdminRole(),"Active");
                    //hospitalEnterprise.setAddress(address);
                        }
//                }
//            }
            
            
         
        }
    }

}
