/*
 * Copyright (C) 2014 Abhishek
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package userInterface.pharmaceuticalCompany;

import baseClasses.enterprise.CityEnterprise;
import baseClasses.enterprise.Enterprise;
import baseClasses.enterprise.PharmaceuticalCompanyEnterprise;
import baseClasses.network.Network;
import baseClasses.organization.Organization;
import baseClasses.userAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;


/**
 *
 * @author Abhishek
 */
public class PharmaceuticalAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form GovernmentAdminWorkArea
     */
    private Network internationalNetwork;
    private PharmaceuticalCompanyEnterprise pharmaceuticalCompanyEnterprise;
    private Organization inOrganization;
    //private CountryEnterprise countryEnterprise;
    private UserAccount userAccount;
    private CityEnterprise inCityEnterprise;
    
    public PharmaceuticalAdminWorkArea(Network internationalNetwork, PharmaceuticalCompanyEnterprise pharmaceuticalCompanyEnterprise,CityEnterprise inCityEnterprise, UserAccount userAccount) {
        initComponents();
        this.internationalNetwork = internationalNetwork;
        this.pharmaceuticalCompanyEnterprise = pharmaceuticalCompanyEnterprise;
        this.inOrganization = inOrganization;
        //this.countryEnterprise = countryEnterprise;
        this.userAccount = userAccount;
        this.inCityEnterprise = inCityEnterprise;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnAddNewManufacturingOrganization = new javax.swing.JButton();
        btnManageManufacturingOrganizations = new javax.swing.JButton();
        btnAddNewDistributorOrganization = new javax.swing.JButton();
        btnManageDistributorOrganizations = new javax.swing.JButton();
        btnAddNewDrug = new javax.swing.JButton();
        btnDrugApprovalRequestDetails = new javax.swing.JButton();
        btnDrugDetails1 = new javax.swing.JButton();
        btnComposeNewMail = new javax.swing.JButton();
        btnCheckMails = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAddNewManufacturingOrganization.setBackground(new java.awt.Color(255, 255, 255));
        btnAddNewManufacturingOrganization.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddNewManufacturingOrganization.setForeground(new java.awt.Color(0, 153, 0));
        btnAddNewManufacturingOrganization.setText("Add New Manufacturing Organization");
        btnAddNewManufacturingOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewManufacturingOrganizationActionPerformed(evt);
            }
        });

        btnManageManufacturingOrganizations.setBackground(new java.awt.Color(255, 255, 255));
        btnManageManufacturingOrganizations.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManageManufacturingOrganizations.setForeground(new java.awt.Color(0, 153, 0));
        btnManageManufacturingOrganizations.setText("Manage Manufacturing Organizations");
        btnManageManufacturingOrganizations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageManufacturingOrganizationsActionPerformed(evt);
            }
        });

        btnAddNewDistributorOrganization.setBackground(new java.awt.Color(255, 255, 255));
        btnAddNewDistributorOrganization.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddNewDistributorOrganization.setForeground(new java.awt.Color(0, 153, 0));
        btnAddNewDistributorOrganization.setText("Add New Distributor Organization");
        btnAddNewDistributorOrganization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewDistributorOrganizationActionPerformed(evt);
            }
        });

        btnManageDistributorOrganizations.setBackground(new java.awt.Color(255, 255, 255));
        btnManageDistributorOrganizations.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManageDistributorOrganizations.setForeground(new java.awt.Color(0, 153, 0));
        btnManageDistributorOrganizations.setText("Manage Distributor Organizations");
        btnManageDistributorOrganizations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDistributorOrganizationsActionPerformed(evt);
            }
        });

        btnAddNewDrug.setBackground(new java.awt.Color(255, 255, 255));
        btnAddNewDrug.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddNewDrug.setForeground(new java.awt.Color(0, 153, 0));
        btnAddNewDrug.setText("Add New Drug");
        btnAddNewDrug.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewDrugActionPerformed(evt);
            }
        });

        btnDrugApprovalRequestDetails.setBackground(new java.awt.Color(255, 255, 255));
        btnDrugApprovalRequestDetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDrugApprovalRequestDetails.setForeground(new java.awt.Color(0, 153, 0));
        btnDrugApprovalRequestDetails.setText("Drug Approval Request Details");
        btnDrugApprovalRequestDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrugApprovalRequestDetailsActionPerformed(evt);
            }
        });

        btnDrugDetails1.setBackground(new java.awt.Color(255, 255, 255));
        btnDrugDetails1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDrugDetails1.setForeground(new java.awt.Color(0, 153, 0));
        btnDrugDetails1.setText("Drug Details");
        btnDrugDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrugDetails1ActionPerformed(evt);
            }
        });

        btnComposeNewMail.setBackground(new java.awt.Color(255, 255, 255));
        btnComposeNewMail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnComposeNewMail.setForeground(new java.awt.Color(0, 153, 0));
        btnComposeNewMail.setText("Compose Mail");
        btnComposeNewMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComposeNewMailActionPerformed(evt);
            }
        });

        btnCheckMails.setBackground(new java.awt.Color(255, 255, 255));
        btnCheckMails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCheckMails.setForeground(new java.awt.Color(0, 153, 0));
        btnCheckMails.setText("Inbox");
        btnCheckMails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckMailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddNewManufacturingOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnManageManufacturingOrganizations, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAddNewDrug, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAddNewDistributorOrganization, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnManageDistributorOrganizations, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDrugDetails1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCheckMails, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnComposeNewMail, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                    .addComponent(btnDrugApprovalRequestDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(247, 247, 247))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNewManufacturingOrganization)
                    .addComponent(btnAddNewDrug)
                    .addComponent(btnManageManufacturingOrganizations)
                    .addComponent(btnDrugApprovalRequestDetails))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNewDistributorOrganization)
                    .addComponent(btnManageDistributorOrganizations)
                    .addComponent(btnDrugDetails1)
                    .addComponent(btnCheckMails)
                    .addComponent(btnComposeNewMail))
                .addGap(23, 23, 23))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseClasses/healtech logo.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 1587, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 525, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewManufacturingOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewManufacturingOrganizationActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setBottomComponent(new userInterface.pharmaceuticalCompany.AddNewManufacturer(internationalNetwork, pharmaceuticalCompanyEnterprise, inCityEnterprise));
        
    }//GEN-LAST:event_btnAddNewManufacturingOrganizationActionPerformed

    private void btnManageManufacturingOrganizationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageManufacturingOrganizationsActionPerformed
        // TODO add your handling code here:
        JPanel manageManufacturerProfileCard = new JPanel();
        manageManufacturerProfileCard.setLayout(new CardLayout());
        
        manageManufacturerProfileCard.add(new ManageManufacturerProfiles(internationalNetwork,manageManufacturerProfileCard,pharmaceuticalCompanyEnterprise,inCityEnterprise));
        CardLayout layout = (CardLayout) manageManufacturerProfileCard.getLayout();
        layout.next(manageManufacturerProfileCard);
        jSplitPane1.setBottomComponent(manageManufacturerProfileCard);
    }//GEN-LAST:event_btnManageManufacturingOrganizationsActionPerformed

    private void btnAddNewDistributorOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewDistributorOrganizationActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setBottomComponent(new userInterface.pharmaceuticalCompany.AddNewDistributor(internationalNetwork,pharmaceuticalCompanyEnterprise,inCityEnterprise));
    }//GEN-LAST:event_btnAddNewDistributorOrganizationActionPerformed

    private void btnManageDistributorOrganizationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDistributorOrganizationsActionPerformed
        // TODO add your handling code here:
         //jSplitPane1.setBottomComponent(new userInterface.pharmaceuticalCompany.EditDistributorDetails(internationalNetwork));
         JPanel manageDistibutorrProfileCard = new JPanel();
        manageDistibutorrProfileCard.setLayout(new CardLayout());
        
        manageDistibutorrProfileCard.add(new ManageDistributorProfiles(internationalNetwork,manageDistibutorrProfileCard,pharmaceuticalCompanyEnterprise,inCityEnterprise));
        CardLayout layout = (CardLayout) manageDistibutorrProfileCard.getLayout();
        layout.next(manageDistibutorrProfileCard);
        jSplitPane1.setBottomComponent(manageDistibutorrProfileCard);
    }//GEN-LAST:event_btnManageDistributorOrganizationsActionPerformed

    private void btnAddNewDrugActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewDrugActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setBottomComponent(new AddNewDrug(internationalNetwork, pharmaceuticalCompanyEnterprise, inCityEnterprise, userAccount));
    }//GEN-LAST:event_btnAddNewDrugActionPerformed

    private void btnDrugApprovalRequestDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrugApprovalRequestDetailsActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setBottomComponent(new DrugRequestDetailsPanel(pharmaceuticalCompanyEnterprise, userAccount));
    }//GEN-LAST:event_btnDrugApprovalRequestDetailsActionPerformed

    private void btnDrugDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrugDetails1ActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setBottomComponent(new DrugDetails(pharmaceuticalCompanyEnterprise, userAccount));
    }//GEN-LAST:event_btnDrugDetails1ActionPerformed

    private void btnComposeNewMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComposeNewMailActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new ComposeMail(internationalNetwork, userAccount));

    }//GEN-LAST:event_btnComposeNewMailActionPerformed

    private void btnCheckMailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckMailsActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new Inbox(userAccount.getWorkQueue()));

    }//GEN-LAST:event_btnCheckMailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewDistributorOrganization;
    private javax.swing.JButton btnAddNewDrug;
    private javax.swing.JButton btnAddNewManufacturingOrganization;
    private javax.swing.JButton btnCheckMails;
    private javax.swing.JButton btnComposeNewMail;
    private javax.swing.JButton btnDrugApprovalRequestDetails;
    private javax.swing.JButton btnDrugDetails1;
    private javax.swing.JButton btnManageDistributorOrganizations;
    private javax.swing.JButton btnManageManufacturingOrganizations;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
