/*
 * Copyright (C) 2014 Abhishek
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package userInterface.systemAdmin;

import baseClasses.network.Network;

/**
 *
 * @author Abhishek
 */
public class HealTechLocalWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form ManageHealTechLocalsWorkArea
     */
    Network internationalNetwork;
    public HealTechLocalWorkArea(Network internationalNetwork) {
        initComponents();
        this.internationalNetwork = internationalNetwork;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnAddNewHealTechLocal = new javax.swing.JButton();
        btnManageHealTechLocals = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(100);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1591, 820));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1192, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnAddNewHealTechLocal.setBackground(new java.awt.Color(255, 255, 255));
        btnAddNewHealTechLocal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddNewHealTechLocal.setForeground(new java.awt.Color(0, 153, 0));
        btnAddNewHealTechLocal.setText("Add New HealTech Local");
        btnAddNewHealTechLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewHealTechLocalActionPerformed(evt);
            }
        });

        btnManageHealTechLocals.setBackground(new java.awt.Color(255, 255, 255));
        btnManageHealTechLocals.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManageHealTechLocals.setForeground(new java.awt.Color(0, 153, 0));
        btnManageHealTechLocals.setText("Manage HealTech Locals");
        btnManageHealTechLocals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageHealTechLocalsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(btnAddNewHealTechLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(236, 236, 236)
                .addComponent(btnManageHealTechLocals, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(289, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNewHealTechLocal)
                    .addComponent(btnManageHealTechLocals))
                .addGap(31, 31, 31))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewHealTechLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewHealTechLocalActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setBottomComponent(new AddNewHealTechLocal(internationalNetwork));
        
    }//GEN-LAST:event_btnAddNewHealTechLocalActionPerformed

    private void btnManageHealTechLocalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageHealTechLocalsActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setBottomComponent(new ManageHealTechLocalPanel(internationalNetwork));
    }//GEN-LAST:event_btnManageHealTechLocalsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewHealTechLocal;
    private javax.swing.JButton btnManageHealTechLocals;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
