/*
 * Copyright (C) 2014 Abhishek
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package userInterface.systemAdmin;

import baseClasses.enterprise.CountryEnterprise;
import baseClasses.enterprise.Enterprise;
import baseClasses.network.Network;
import baseClasses.roles.CountryRole;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhishek
 */
public class ManageCountriesPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCountriesPanel
     */
    Network internationalNetwork;
    
    public ManageCountriesPanel(Network internationalNetwork) {
        initComponents();
        this.internationalNetwork = internationalNetwork;
        populateCountryList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        btnDeleteCountry = new javax.swing.JButton();
        btnRenameCountry = new javax.swing.JButton();
        txtName = new javax.swing.JTextField();
        btnAddNewCountry = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblCountryList = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1591, 820));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseClasses/healtech logo.PNG"))); // NOI18N

        lblName1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblName1.setForeground(new java.awt.Color(0, 153, 51));
        lblName1.setText("Manage Countries");

        btnDeleteCountry.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteCountry.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDeleteCountry.setForeground(new java.awt.Color(0, 153, 0));
        btnDeleteCountry.setText("Delete Country");
        btnDeleteCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCountryActionPerformed(evt);
            }
        });

        btnRenameCountry.setBackground(new java.awt.Color(255, 255, 255));
        btnRenameCountry.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRenameCountry.setForeground(new java.awt.Color(0, 153, 0));
        btnRenameCountry.setText("Rename Country");
        btnRenameCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenameCountryActionPerformed(evt);
            }
        });

        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        btnAddNewCountry.setBackground(new java.awt.Color(255, 255, 255));
        btnAddNewCountry.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddNewCountry.setForeground(new java.awt.Color(0, 153, 0));
        btnAddNewCountry.setText("Add New Country");
        btnAddNewCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewCountryActionPerformed(evt);
            }
        });

        tblCountryList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblCountryList.setForeground(new java.awt.Color(0, 153, 51));
        tblCountryList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Country"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblCountryList);
        if (tblCountryList.getColumnModel().getColumnCount() > 0) {
            tblCountryList.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(377, 377, 377)
                .addComponent(lblName1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(btnDeleteCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 910, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAddNewCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(133, 133, 133))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(387, 387, 387)
                    .addComponent(btnRenameCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(463, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lblName1)
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDeleteCountry)
                            .addComponent(btnAddNewCountry))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 48, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(164, 164, 164)
                    .addComponent(btnRenameCountry)
                    .addContainerGap(484, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCountryActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblCountryList.getSelectedRow();
        CountryEnterprise countryEnterprise = (CountryEnterprise)tblCountryList.getValueAt(selectedRow, 0);
        internationalNetwork.getEnterpriseDirectory().getEnterpriseList().remove(countryEnterprise);
    }//GEN-LAST:event_btnDeleteCountryActionPerformed

    private void btnRenameCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenameCountryActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = tblCountryList.getSelectedRow();
        CountryEnterprise countryEnterprise = (CountryEnterprise)tblCountryList.getValueAt(selectedRow, 0);
        
        String newCountryName = txtName.getText();
        
        countryEnterprise.setName(newCountryName);
    }//GEN-LAST:event_btnRenameCountryActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnAddNewCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewCountryActionPerformed
        // TODO add your handling code here:
        String newCountryName = txtName.getText();
        //internationalNetwork.getEnterpriseDirectory().getEnterpriseList().add(new CountryEnterprise(newCountryName));
        CountryEnterprise countryEnterprise =(CountryEnterprise) internationalNetwork.getEnterpriseDirectory().createAndAddEnterprise(txtName.getText(), 
                Enterprise.EnterpriseType.Country,txtName.getText(),txtName.getText(),new CountryRole(),"Active",null);
    }//GEN-LAST:event_btnAddNewCountryActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewCountry;
    private javax.swing.JButton btnDeleteCountry;
    private javax.swing.JButton btnRenameCountry;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblName1;
    private javax.swing.JTable tblCountryList;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private void populateCountryList()
    {
        DefaultTableModel dtm = (DefaultTableModel) tblCountryList.getModel();
        dtm.setRowCount(0);
        CountryEnterprise countryEnterprise;
        for(Enterprise country: internationalNetwork.getEnterpriseDirectory().getEnterpriseList())
        {
            countryEnterprise = (CountryEnterprise) country;
            Object[] row = new Object[1];
            row[0] = countryEnterprise;
            dtm.addRow(row);
        }
        
    }
}
