/*
 * Copyright (C) 2014 Abhishek
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package userInterface.systemAdmin;

import baseClasses.enterprise.CityEnterprise;
import baseClasses.enterprise.CountryEnterprise;
import baseClasses.enterprise.Enterprise;
import baseClasses.enterprise.StateEnterprise;
import baseClasses.network.Network;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Abhishek
 */
public class ManageCitiesPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageCityPanel
     */
    Network internationalNetwork;
    
    public ManageCitiesPanel(Network internationalNetwork) {
        initComponents();
        this.internationalNetwork = internationalNetwork;
        populateCountryList();
        cmbStateList.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblSelectCountry = new javax.swing.JLabel();
        lblName2 = new javax.swing.JLabel();
        cmbCountryList = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCityList = new javax.swing.JTable();
        txtName = new javax.swing.JTextField();
        btnRenameCity = new javax.swing.JButton();
        btnAddNewCity = new javax.swing.JButton();
        btnDeleteCity = new javax.swing.JButton();
        lblSelectCountry1 = new javax.swing.JLabel();
        cmbStateList = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1591, 820));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseClasses/healtech logo.PNG"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1480, 890, -1, -1));

        lblSelectCountry.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSelectCountry.setForeground(new java.awt.Color(0, 153, 51));
        lblSelectCountry.setText("Select Country:");
        add(lblSelectCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 116, -1, -1));

        lblName2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblName2.setForeground(new java.awt.Color(0, 153, 51));
        lblName2.setText("Manage Cities");
        add(lblName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 21, -1, -1));

        cmbCountryList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbCountryList.setForeground(new java.awt.Color(0, 204, 51));
        cmbCountryList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCountryListActionPerformed(evt);
            }
        });
        add(cmbCountryList, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 113, 183, -1));

        tblCityList.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblCityList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "City"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblCityList);
        if (tblCityList.getColumnModel().getColumnCount() > 0) {
            tblCityList.getColumnModel().getColumn(0).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 239, 362, 542));

        txtName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(902, 240, 261, -1));

        btnRenameCity.setBackground(new java.awt.Color(255, 255, 255));
        btnRenameCity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnRenameCity.setForeground(new java.awt.Color(0, 153, 0));
        btnRenameCity.setText("Rename City");
        btnRenameCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRenameCityActionPerformed(evt);
            }
        });
        add(btnRenameCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 239, 261, -1));

        btnAddNewCity.setBackground(new java.awt.Color(255, 255, 255));
        btnAddNewCity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddNewCity.setForeground(new java.awt.Color(0, 153, 0));
        btnAddNewCity.setText("Add New City");
        btnAddNewCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewCityActionPerformed(evt);
            }
        });
        add(btnAddNewCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 360, 261, -1));

        btnDeleteCity.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteCity.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnDeleteCity.setForeground(new java.awt.Color(0, 153, 0));
        btnDeleteCity.setText("Delete City");
        btnDeleteCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCityActionPerformed(evt);
            }
        });
        add(btnDeleteCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(485, 352, 261, -1));

        lblSelectCountry1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblSelectCountry1.setForeground(new java.awt.Color(0, 153, 51));
        lblSelectCountry1.setText("Select State:");
        add(lblSelectCountry1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 174, -1, -1));

        cmbStateList.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbStateList.setForeground(new java.awt.Color(0, 204, 51));
        cmbStateList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbStateListActionPerformed(evt);
            }
        });
        add(cmbStateList, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 171, 183, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCountryListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCountryListActionPerformed
        // TODO add your handling code here:
        cmbStateList.setEnabled(true);
        populateStateList((CountryEnterprise) cmbCountryList.getSelectedItem());
        
    }//GEN-LAST:event_cmbCountryListActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void btnRenameCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRenameCityActionPerformed
        // TODO add your handling code here:
         int selectedRow = tblCityList.getSelectedRow();
        CityEnterprise cityEnterprise = (CityEnterprise)tblCityList.getValueAt(selectedRow, 0);
        
        String newCityName = txtName.getText();
        
        cityEnterprise.setName(newCityName);
    }//GEN-LAST:event_btnRenameCityActionPerformed

    private void btnAddNewCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewCityActionPerformed
        // TODO add your handling code here:
        StateEnterprise stateEnterprise = (StateEnterprise) cmbStateList.getSelectedItem();
        CityEnterprise cityEnterprise =(CityEnterprise) stateEnterprise.getStateNetwork().getEnterpriseDirectory().createAndAddEnterprise(txtName.getText(), Enterprise.EnterpriseType.City,null,null,null,null,null);
        //stateEnterprise.getStateNetwork().getEnterpriseDirectory().getEnterpriseList().add(stateEnterprise);
        populateCityTable(stateEnterprise);
    }//GEN-LAST:event_btnAddNewCityActionPerformed

    private void btnDeleteCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCityActionPerformed
        // TODO add your handling code here:
        StateEnterprise stateEnterprise = (StateEnterprise) cmbStateList.getSelectedItem();
        stateEnterprise.getStateNetwork().getEnterpriseDirectory().getEnterpriseList().remove((StateEnterprise)tblCityList.getValueAt(tblCityList.getSelectedRow(), 0));
    }//GEN-LAST:event_btnDeleteCityActionPerformed

    private void cmbStateListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbStateListActionPerformed
        // TODO add your handling code here:
        populateCityTable((StateEnterprise)cmbStateList.getSelectedItem());
    }//GEN-LAST:event_cmbStateListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewCity;
    private javax.swing.JButton btnDeleteCity;
    private javax.swing.JButton btnRenameCity;
    private javax.swing.JComboBox cmbCountryList;
    private javax.swing.JComboBox cmbStateList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblSelectCountry;
    private javax.swing.JLabel lblSelectCountry1;
    private javax.swing.JTable tblCityList;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables

    private void populateCountryList()
    {
        cmbCountryList.removeAllItems();
        CountryEnterprise countryEnterprise;
        
        System.out.println("**************************************************************************************************");
        System.out.println(internationalNetwork);
        System.out.println(internationalNetwork.getEnterpriseDirectory());
        for(Enterprise country: internationalNetwork.getEnterpriseDirectory().getEnterpriseList())
        {
            cmbCountryList.addItem((CountryEnterprise) country);
        }
        
    }

    private void populateStateList(CountryEnterprise countryEnterprise)
    {
     
        cmbStateList.removeAllItems();
        
        
        for(Enterprise state: countryEnterprise.getCountryNetwork().getEnterpriseDirectory().getEnterpriseList())
        {
            if(state.getClass() ==  StateEnterprise.class)
            cmbStateList.addItem((StateEnterprise) state);
            
        }
        
    }

    private void populateCityTable(StateEnterprise stateEnterprise)
    {
            
        DefaultTableModel dtm = (DefaultTableModel) tblCityList.getModel();
        dtm.setRowCount(0);
        
        for(Enterprise city: stateEnterprise.getStateNetwork().getEnterpriseDirectory().getEnterpriseList())
        {
            Object[] row = new Object[1];
            row[0] = (CityEnterprise) city;
            
            dtm.addRow(row);
            
        }
        
    }
}
