/*
 * Copyright (C) 2014 Abhishek
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package userInterface.manufacturer;

import baseClasses.enterprise.Enterprise;
import baseClasses.enterprise.PharmaceuticalCompanyEnterprise;
import baseClasses.network.Network;
import baseClasses.organization.ManufacturingOrganization;
import baseClasses.organization.Organization;
import baseClasses.userAccount.UserAccount;

/**
 *
 * @author Abhishek
 */
public class ManufacturingAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form GovernmentAdminWorkArea
     */
    Network internationalNetwork;
    Enterprise inEnterprise;
    Organization inOrganization;
    UserAccount userAccount;
    private PharmaceuticalCompanyEnterprise pharmaceuticalCompanyEnterprise;
    private ManufacturingOrganization manufacturingOrganization;
    
    public ManufacturingAdminWorkArea(Network internationalNetwork, Enterprise inEnterprise, Organization inOrganization, UserAccount userAccount) {
        initComponents();
        this.internationalNetwork = internationalNetwork;
        this.inEnterprise = inEnterprise;
        this.inOrganization = inOrganization;
        this.userAccount = userAccount;
        

        if(inEnterprise.getClass() == PharmaceuticalCompanyEnterprise.class)
        {
            pharmaceuticalCompanyEnterprise = (PharmaceuticalCompanyEnterprise) inEnterprise;
        }
        
        if(inOrganization.getClass() == ManufacturingOrganization.class)
        {
            manufacturingOrganization = (ManufacturingOrganization) inOrganization;
        }
        
        System.out.println("Manufacturing ORganization" + manufacturingOrganization);
                 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnManufactureDrugs = new javax.swing.JButton();
        btnManageDrugs = new javax.swing.JButton();
        btnMedicineDetails = new javax.swing.JButton();
        btnMedicineRequestDetails = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnManufactureDrugs.setBackground(new java.awt.Color(255, 255, 255));
        btnManufactureDrugs.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManufactureDrugs.setForeground(new java.awt.Color(0, 153, 0));
        btnManufactureDrugs.setText("Add New Medicines");
        btnManufactureDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManufactureDrugsActionPerformed(evt);
            }
        });

        btnManageDrugs.setBackground(new java.awt.Color(255, 255, 255));
        btnManageDrugs.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManageDrugs.setForeground(new java.awt.Color(0, 153, 0));
        btnManageDrugs.setText("Manage Medicines");
        btnManageDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDrugsActionPerformed(evt);
            }
        });

        btnMedicineDetails.setBackground(new java.awt.Color(255, 255, 255));
        btnMedicineDetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMedicineDetails.setForeground(new java.awt.Color(0, 153, 0));
        btnMedicineDetails.setText("Medicine Details");
        btnMedicineDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicineDetailsActionPerformed(evt);
            }
        });

        btnMedicineRequestDetails.setBackground(new java.awt.Color(255, 255, 255));
        btnMedicineRequestDetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnMedicineRequestDetails.setForeground(new java.awt.Color(0, 153, 0));
        btnMedicineRequestDetails.setText("Medicine Request Details");
        btnMedicineRequestDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedicineRequestDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnManufactureDrugs, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(btnMedicineRequestDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnManageDrugs, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnMedicineDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnManufactureDrugs)
                    .addComponent(btnManageDrugs)
                    .addComponent(btnMedicineRequestDetails))
                .addGap(18, 18, 18)
                .addComponent(btnMedicineDetails)
                .addGap(0, 34, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseClasses/healtech logo.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 1211, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 529, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManufactureDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManufactureDrugsActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setBottomComponent(new ManufactureMedicines(internationalNetwork, inEnterprise, userAccount, manufacturingOrganization));
        
    }//GEN-LAST:event_btnManufactureDrugsActionPerformed

    private void btnManageDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDrugsActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setBottomComponent(new ManageMedicines(inEnterprise, userAccount, manufacturingOrganization));
    }//GEN-LAST:event_btnManageDrugsActionPerformed

    private void btnMedicineDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicineDetailsActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setBottomComponent(new MedicineDetails(pharmaceuticalCompanyEnterprise, userAccount, manufacturingOrganization));
    }//GEN-LAST:event_btnMedicineDetailsActionPerformed

    private void btnMedicineRequestDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedicineRequestDetailsActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setBottomComponent(new MedicineRequestDetailsPanel(pharmaceuticalCompanyEnterprise, userAccount, manufacturingOrganization));
    }//GEN-LAST:event_btnMedicineRequestDetailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageDrugs;
    private javax.swing.JButton btnManufactureDrugs;
    private javax.swing.JButton btnMedicineDetails;
    private javax.swing.JButton btnMedicineRequestDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
