/*
 * Copyright (C) 2014 Abhishek
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package userInterface.hospital;

import baseClasses.enterprise.HospitalEnterprise;
import baseClasses.network.Network;
import baseClasses.organization.Organization;
import baseClasses.userAccount.UserAccount;

/**
 *
 * @author Abhishek
 */


public class HospitalAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form HospitalAdminWorkArea
     */
        Network internationalNetwork;
    HospitalEnterprise hospitalEnterprise;
    UserAccount userAccount;
    Organization inOrganization;
    
    public HospitalAdminWorkArea(Network internationalNetwork, HospitalEnterprise hospitalEnterprise, UserAccount userAccount, Organization inOrganization) {
        initComponents();
        this.internationalNetwork = internationalNetwork;
        this.hospitalEnterprise = hospitalEnterprise;
        this.userAccount = userAccount;
        this.inOrganization = inOrganization;
        System.out.println("Printing from HospitalAdminWorkArea: " + hospitalEnterprise);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnManageDoctors = new javax.swing.JButton();
        btnManagePatients = new javax.swing.JButton();
        btnManageLabAssistants = new javax.swing.JButton();
        btnComposeNewMail = new javax.swing.JButton();
        btnCheckMails = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(300);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseClasses/healtech logo.PNG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 692, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 502, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        jSplitPane1.setRightComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/baseClasses/healtech small.png"))); // NOI18N

        btnManageDoctors.setBackground(new java.awt.Color(255, 255, 255));
        btnManageDoctors.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManageDoctors.setForeground(new java.awt.Color(0, 153, 0));
        btnManageDoctors.setText("Manage Doctors");
        btnManageDoctors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDoctorsActionPerformed(evt);
            }
        });

        btnManagePatients.setBackground(new java.awt.Color(255, 255, 255));
        btnManagePatients.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManagePatients.setForeground(new java.awt.Color(0, 153, 0));
        btnManagePatients.setText("Manage Patients");
        btnManagePatients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePatientsActionPerformed(evt);
            }
        });

        btnManageLabAssistants.setBackground(new java.awt.Color(255, 255, 255));
        btnManageLabAssistants.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManageLabAssistants.setForeground(new java.awt.Color(0, 153, 0));
        btnManageLabAssistants.setText("Manage Lab Assistants");
        btnManageLabAssistants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageLabAssistantsActionPerformed(evt);
            }
        });

        btnComposeNewMail.setBackground(new java.awt.Color(255, 255, 255));
        btnComposeNewMail.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnComposeNewMail.setForeground(new java.awt.Color(0, 153, 0));
        btnComposeNewMail.setText("Compose Mail");
        btnComposeNewMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComposeNewMailActionPerformed(evt);
            }
        });

        btnCheckMails.setBackground(new java.awt.Color(255, 255, 255));
        btnCheckMails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnCheckMails.setForeground(new java.awt.Color(0, 153, 0));
        btnCheckMails.setText("Inbox");
        btnCheckMails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckMailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCheckMails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnComposeNewMail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageDoctors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManagePatients, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageLabAssistants, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnManageDoctors)
                .addGap(39, 39, 39)
                .addComponent(btnManagePatients)
                .addGap(44, 44, 44)
                .addComponent(btnManageLabAssistants)
                .addGap(31, 31, 31)
                .addComponent(btnComposeNewMail)
                .addGap(36, 36, 36)
                .addComponent(btnCheckMails)
                .addGap(0, 165, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageDoctorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDoctorsActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new ManageDoctors(internationalNetwork, hospitalEnterprise,inOrganization));

    }//GEN-LAST:event_btnManageDoctorsActionPerformed

    private void btnManagePatientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePatientsActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new ManagePatients(internationalNetwork, hospitalEnterprise));
    }//GEN-LAST:event_btnManagePatientsActionPerformed

    private void btnManageLabAssistantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageLabAssistantsActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new ManageLabAssistants(internationalNetwork, hospitalEnterprise));
    }//GEN-LAST:event_btnManageLabAssistantsActionPerformed

    private void btnComposeNewMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComposeNewMailActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new ComposeMail(internationalNetwork, userAccount));

    }//GEN-LAST:event_btnComposeNewMailActionPerformed

    private void btnCheckMailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckMailsActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setRightComponent(new Inbox(userAccount.getWorkQueue()));

    }//GEN-LAST:event_btnCheckMailsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckMails;
    private javax.swing.JButton btnComposeNewMail;
    private javax.swing.JButton btnManageDoctors;
    private javax.swing.JButton btnManageLabAssistants;
    private javax.swing.JButton btnManagePatients;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
