/*
 * Copyright (C) 2014 Abhishek
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package userInterface.hospital;

import baseClasses.enterprise.HospitalEnterprise;
import baseClasses.network.Network;
import baseClasses.organization.DoctorOrganization;
import baseClasses.organization.Organization;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Abhishek
 */
public class ManageDoctors extends javax.swing.JPanel {

    /**
     * Creates new form ManageDoctors
     */
    Network internationalNetwork;
    HospitalEnterprise hospitalEnterprise;
    Organization inOrganization;
    DoctorOrganization doctorOrganization = null;

    public ManageDoctors(Network internationalNetwork, HospitalEnterprise hospitalEnterprise, Organization inOrganization) {
        initComponents();
        this.internationalNetwork = internationalNetwork;
        this.hospitalEnterprise = hospitalEnterprise;
        this.inOrganization = inOrganization;

        for (Organization org : hospitalEnterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org.getClass() == DoctorOrganization.class) {
                doctorOrganization = (DoctorOrganization) inOrganization;
            }
        }

        System.out.println("Printing from ManageDoctors: " + hospitalEnterprise);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnAddNewDoctor = new javax.swing.JButton();
        btnManageDoctors1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(100);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAddNewDoctor.setBackground(new java.awt.Color(255, 255, 255));
        btnAddNewDoctor.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddNewDoctor.setForeground(new java.awt.Color(0, 153, 0));
        btnAddNewDoctor.setText("Add New Doctor");
        btnAddNewDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewDoctorActionPerformed(evt);
            }
        });

        btnManageDoctors1.setBackground(new java.awt.Color(255, 255, 255));
        btnManageDoctors1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManageDoctors1.setForeground(new java.awt.Color(0, 153, 0));
        btnManageDoctors1.setText("Manage Doctors");
        btnManageDoctors1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDoctors1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnAddNewDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(259, 259, 259)
                .addComponent(btnManageDoctors1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(469, 469, 469))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNewDoctor)
                    .addComponent(btnManageDoctors1))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1224, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewDoctorActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setBottomComponent(new AddNewDoctorPanel(internationalNetwork, hospitalEnterprise));

    }//GEN-LAST:event_btnAddNewDoctorActionPerformed

    private void btnManageDoctors1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDoctors1ActionPerformed
        // TODO add your handling code here:
        JPanel updateDoctorCard = new JPanel();
        updateDoctorCard.setLayout(new CardLayout());
        CardLayout layout = (CardLayout) updateDoctorCard.getLayout();

        updateDoctorCard.add(new ManageDoctorInfo(internationalNetwork, hospitalEnterprise, updateDoctorCard, doctorOrganization));
        layout.next(updateDoctorCard);

        jSplitPane1.setBottomComponent(updateDoctorCard);
    }//GEN-LAST:event_btnManageDoctors1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewDoctor;
    private javax.swing.JButton btnManageDoctors1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
