/*
 * Copyright (C) 2014 Abhishek
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package userInterface.hospital;

import baseClasses.enterprise.HospitalEnterprise;
import baseClasses.network.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Abhishek
 */
public class ManageLabAssistants extends javax.swing.JPanel {

    /**
     * Creates new form ManageLabAssistants
     */
    Network internationalNetwork;
    HospitalEnterprise hospitalEnterprise;
    
    public ManageLabAssistants(Network internationalNetwork,HospitalEnterprise hospitalEnterprise)
    {
        initComponents();
        this.internationalNetwork = internationalNetwork;
        this.hospitalEnterprise = hospitalEnterprise;
        System.out.println("Printing from ManageLabAssistants: " + hospitalEnterprise);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        btnAddNewLabAssistant = new javax.swing.JButton();
        btnManageLabAssistant = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jSplitPane1.setDividerLocation(100);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnAddNewLabAssistant.setBackground(new java.awt.Color(255, 255, 255));
        btnAddNewLabAssistant.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAddNewLabAssistant.setForeground(new java.awt.Color(0, 153, 0));
        btnAddNewLabAssistant.setText("Add New Lab Assistant");
        btnAddNewLabAssistant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewLabAssistantActionPerformed(evt);
            }
        });

        btnManageLabAssistant.setBackground(new java.awt.Color(255, 255, 255));
        btnManageLabAssistant.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnManageLabAssistant.setForeground(new java.awt.Color(0, 153, 0));
        btnManageLabAssistant.setText("Manage Lab Assistant");
        btnManageLabAssistant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageLabAssistantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(btnAddNewLabAssistant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(259, 259, 259)
                .addComponent(btnManageLabAssistant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(469, 469, 469))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNewLabAssistant)
                    .addComponent(btnManageLabAssistant))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1328, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(jPanel2);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewLabAssistantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewLabAssistantActionPerformed
        // TODO add your handling code here:
        jSplitPane1.setBottomComponent(new AddNewLabAssistantPanel(internationalNetwork, hospitalEnterprise));

    }//GEN-LAST:event_btnAddNewLabAssistantActionPerformed

    private void btnManageLabAssistantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageLabAssistantActionPerformed
        // TODO add your handling code here:
        JPanel updateLabAssistantCard = new JPanel();
        updateLabAssistantCard.setLayout(new CardLayout());
        CardLayout layout = (CardLayout) updateLabAssistantCard.getLayout();
        
        updateLabAssistantCard.add(new ManageLabAssistantInfo(internationalNetwork, hospitalEnterprise, updateLabAssistantCard));
        layout.next(updateLabAssistantCard);
        
        jSplitPane1.setBottomComponent(updateLabAssistantCard);
    }//GEN-LAST:event_btnManageLabAssistantActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewLabAssistant;
    private javax.swing.JButton btnManageLabAssistant;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
